apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: circleci-runner
spec:
  generators:
    - list:
  template:
    metadata:
      name: circleci-runner
    spec:
      destination:
        name: in-cluster
        namespace: circleci
      source:
        repoURL: https://github.com/liquorichris/argo.git
        path: circleci-container-agent
        targetRevision: HEAD
        helm:
          values: |-
            agent:
              resourceClasses:
                liquorichris/container-agent:
              customSecret: circleci-agent-token
      sources: []
      project: default
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
          enabled: true
