apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: circleci-container-agent
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: circleci-container-agent
    spec:
      destination:
        name: in-cluster
        namespace: argocd
      source:
        repoURL: https://github.com/liquorichris/argo.git
        path: circleci-container-agent
        targetRevision: HEAD
        plugin:
          name: helmfile
      project: default
      syncPolicy:
        automated:
          selfHeal: true
