apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: circleci-container-agent
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            namespace: circleci
  template:
    metadata:
      name: circleci-container-agent
    spec:
      destination:
        name: in-cluster
        namespace: circleci
      source:
        repoURL: https://github.com/liquorichris/argo.git
        path: circleci-container-agent
        targetRevision: HEAD
        helm:
          valueFiles:
            - values.yaml
      project: default
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true