apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: circleci-agent-token
  namespace: circleci
spec:
  vault:
    name: sdbi-akv-eastus-dev
    object:
      name: circleci-agent-token # name of the akv object
      type: secret # akv object type
  output:
    secret:
      name: circleci-agent-token
      dataKey: liquorichris.container-agent