apiVersion: v1
kind: Secret
metadata:
  name: circleci-container-agent
  namespace: circleci
data:
  liquorichris.container-agent: Njc3MjI0NWM1ODA1YmI5MTNkNjIyNmM3NzcxZmJkNmY3NWNkNWI5NDllZTAwYTM2YmRlNWNhNTU2ZmMwNDhmMmI2MDVlNzgwM2ZhYmNkNGQ=