apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: circleci-container-agent
  namespace: circleci
spec:
  vault:
    name: argo-kv-cl # name of key vault
    object:
      name: circleci-agent-token # name of the akv object
      type: secret # akv object type
