apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: circleci-agent-token
  namespace: circleci
spec:
  vault:
    name: argo-kv-cl # name of key vault
    object:
      name: circleci-agent-token # name of the akv object
      type: secret # akv object type
---
apiVersion: v1
kind: Secret
metadata:
  name: circleci-container-agent
  namespace: circleci
type: Opaque
data:
  liquorichris.class: Y2lyY2xlY2ktYWdlbnQtdG9rZW5AYXp1cmVrZXl2YXVsdA== # base64 encoded value of circleci-agent-token@azurekeyvault