{{- if include "container-agent.create-secret" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "container-agent.fullname" . }}
data:
  {{- include "container-agent.tokens" . | indent 2 }}
{{- end -}}
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: circleci-agent-token
  namespace: circleci
spec:
  vault:
    name: argo-kv-cl # name of key vault
    object:
      name: circleci-agent-token # name of the akv object
      type: secret # akv object type
