# apiVersion: spv.no/v2beta1
# kind: AzureKeyVaultSecret
# metadata:
#   name: circleci-agent-token
#   namespace: circleci
# spec:
#   vault:
#     name: argo-kv-cl
#     object:
#       name: circleci-agent-token
#       type: secret
# #   output:
# #     configMap:
# #       name: circleci-container-agent
# #       dataKey: taskpods
{{- if include "container-agent.create-secret" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "container-agent.fullname" . }}
data:
  {{- include "container-agent.tokens" . | indent 2 }}
{{- end -}}